import '@/styles/globals.css'
// import { Inter } from 'next/font/google'

//INTERNAL IMPORTS
import { Footer, NavBar } from '@/components/componentIndex'

// const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
